Repository Flow-UMC/Flow-Server, pull requests merged in 2023-01, with the labels that each got.

#4 feat: 프로젝트 기본 설정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/flow/FlowApplication.java
  src/main/java/com/flow/controller/CategoryController.java
  src/main/java/com/flow/controller/DetailController.java
  src/main/java/com/flow/controller/FormController.java
  src/main/java/com/flow/controller/KeywordController.java
  src/main/java/com/flow/controller/UserController.java
  src/main/java/com/flow/domain/Budget.java
  src/main/java/com/flow/domain/Category.java
  src/main/java/com/flow/domain/Detail.java
  src/main/java/com/flow/domain/Form.java
  src/main/java/com/flow/domain/Keyword.java
  src/main/java/com/flow/domain/SocialType.java
  src/main/java/com/flow/domain/User.java
  src/main/java/com/flow/dto/CategoryDto.java
  src/main/java/com/flow/dto/DetailDto.java
  src/main/java/com/flow/dto/FormDto.java
  src/main/java/com/flow/dto/KeywordDto.java
  src/main/java/com/flow/dto/UserDto.java
  src/main/java/com/flow/repository/CategoryRepository.java
  src/main/java/com/flow/repository/DetailRepository.java
  src/main/java/com/flow/repository/FormRepository.java
  src/main/java/com/flow/repository/KeywordRepository.java
  src/main/java/com/flow/repository/UserRepository.java
  src/main/java/com/flow/service/CategoryService.java
  src/main/java/com/flow/service/DetailService.java
  src/main/java/com/flow/service/FormService.java
  src/main/java/com/flow/service/KeywordService.java
  src/main/java/com/flow/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/flow/FlowApplicationTests.java
Labels: feature ✨

#11 chore: Detail 컬럼 타입 수정
  src/main/java/com/flow/domain/Detail.java
Labels: setting ⚙

#15 refactor: 패키지 구조 변경
  .gitignore
  build.gradle
  src/main/java/com/flow/config/BaseException.java
  src/main/java/com/flow/config/BaseResponse.java
  src/main/java/com/flow/config/BaseResponseStatus.java
  src/main/java/com/flow/controller/CategoryController.java
  src/main/java/com/flow/controller/DetailController.java
  src/main/java/com/flow/controller/KeywordController.java
  src/main/java/com/flow/domain/Category.java
  src/main/java/com/flow/domain/Detail.java
  src/main/java/com/flow/domain/Keyword.java
  src/main/java/com/flow/dto/CategoryDto.java
  src/main/java/com/flow/dto/DetailDto.java
  src/main/java/com/flow/dto/FormDto.java
  src/main/java/com/flow/dto/KeywordDto.java
  src/main/java/com/flow/dto/UserDto.java
  src/main/java/com/flow/form/controller/FormController.java
  src/main/java/com/flow/form/domain/Form.java
  src/main/java/com/flow/form/dto/FormDto.java
  src/main/java/com/flow/form/repository/FormRepository.java
  src/main/java/com/flow/form/service/FormService.java
  src/main/java/com/flow/repository/CategoryRepository.java
  src/main/java/com/flow/repository/DetailRepository.java
  src/main/java/com/flow/repository/KeywordRepository.java
  src/main/java/com/flow/service/CategoryService.java
  src/main/java/com/flow/service/DetailService.java
  src/main/java/com/flow/service/KeywordService.java
  src/main/java/com/flow/user/controller/UserController.java
  src/main/java/com/flow/user/domain/Budget.java
  src/main/java/com/flow/user/domain/SocialType.java
  src/main/java/com/flow/user/domain/User.java
  src/main/java/com/flow/user/dto/UserDto.java
  src/main/java/com/flow/user/repository/UserRepository.java
  src/main/java/com/flow/user/service/UserService.java
  src/main/resources/application.yml
Labels: refactor ✔

#13 feat: 거래내역 초기화 기능 추가
  src/main/java/com/flow/controller/CategoryController.java
  src/main/java/com/flow/controller/DetailController.java
  src/main/java/com/flow/controller/FormController.java
  src/main/java/com/flow/controller/KeywordController.java
  src/main/java/com/flow/controller/UserController.java
  src/main/java/com/flow/domain/Budget.java
  src/main/java/com/flow/domain/Category.java
  src/main/java/com/flow/domain/Detail.java
  src/main/java/com/flow/domain/Form.java
  src/main/java/com/flow/domain/Keyword.java
  src/main/java/com/flow/domain/SocialType.java
  src/main/java/com/flow/domain/User.java
  src/main/java/com/flow/dto/CategoryDto.java
  src/main/java/com/flow/dto/DetailDto.java
  src/main/java/com/flow/dto/FormDto.java
  src/main/java/com/flow/dto/KeywordDto.java
  src/main/java/com/flow/dto/UserDto.java
  src/main/java/com/flow/flow/calendar/CalendarController.java
  src/main/java/com/flow/flow/calendar/CalendarDao.java
  src/main/java/com/flow/flow/calendar/CalendarProvider.java
  src/main/java/com/flow/flow/config/BaseException.java
  src/main/java/com/flow/flow/config/BaseResponse.java
  src/main/java/com/flow/flow/config/BaseResponseStatus.java
  src/main/java/com/flow/flow/model/Form.java
  src/main/java/com/flow/flow/model/GetCalendarRes.java
  src/main/java/com/flow/flow/model/GetFormReq.java
  src/main/java/com/flow/flow/model/GetFormRes.java
  src/main/java/com/flow/flow/model/GetTotalAmount.java
  src/main/java/com/flow/flow/model/GetTranByDateRes.java
  src/main/java/com/flow/flow/model/PatchBudgetReq.java
  src/main/java/com/flow/flow/model/Transaction.java
  src/main/java/com/flow/flow/setting/SettingController.java
  src/main/java/com/flow/flow/setting/SettingDao.java
  src/main/java/com/flow/flow/setting/SettingProvider.java
  src/main/java/com/flow/flow/setting/SettingService.java
  src/main/java/com/flow/repository/CategoryRepository.java
  src/main/java/com/flow/repository/DetailRepository.java
  src/main/java/com/flow/repository/FormRepository.java
  src/main/java/com/flow/repository/KeywordRepository.java
  src/main/java/com/flow/repository/UserRepository.java
  src/main/java/com/flow/service/CategoryService.java
  src/main/java/com/flow/service/DetailService.java
  src/main/java/com/flow/service/FormService.java
  src/main/java/com/flow/service/KeywordService.java
  src/main/java/com/flow/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature ✨

#17 chore: 파일 구조 수정
  src/main/java/com/flow/FlowApplication.java
  src/main/java/com/flow/config/BaseResponseStatus.java
  src/main/java/com/flow/detail/DetailController.java
  src/main/java/com/flow/detail/DetailDao.java
  src/main/java/com/flow/detail/DetailProvider.java
  src/main/java/com/flow/detail/DetailService.java
  src/main/java/com/flow/keyword/KeywordController.java
  src/main/java/com/flow/keyword/KeywordDao.java
  src/main/java/com/flow/keyword/KeywordProvider.java
  src/main/java/com/flow/keyword/KeywordService.java
  src/main/java/com/flow/model/Detail.java
  src/main/java/com/flow/model/GetDeleteDetailReq.java
  src/main/java/com/flow/model/GetDeleteDetailRes.java
  src/main/java/com/flow/model/GetJoinDetailReq.java
  src/main/java/com/flow/model/GetJoinDetailRes.java
  src/main/java/com/flow/model/Keyword.java
  src/main/java/com/flow/model/ModifyKeyword.java
  src/main/java/com/flow/model/Pagination.java
  src/main/java/com/flow/user/domain/User.java
Labels: feature ✨

#20 feat: 홈, 카테고리 API 구현
  src/main/java/com/flow/category/CategoryController.java
  src/main/java/com/flow/category/CategoryDao.java
  src/main/java/com/flow/category/CategoryProvider.java
  src/main/java/com/flow/category/CategoryService.java
  src/main/java/com/flow/config/BaseResponseStatus.java
  src/main/java/com/flow/home/HomeController.java
  src/main/java/com/flow/home/HomeDao.java
  src/main/java/com/flow/home/HomeProvider.java
  src/main/java/com/flow/model/Category.java
  src/main/java/com/flow/model/CategoryDetail.java
  src/main/java/com/flow/model/Expenditure.java
  src/main/java/com/flow/model/GetCategoryDetailRes.java
  src/main/java/com/flow/model/GetCategoryRes.java
  src/main/java/com/flow/model/GetHomeRes.java
  src/main/java/com/flow/model/PatchCategoryReq.java
  src/main/java/com/flow/model/PostCategoryReq.java
  src/main/resources/application.yml
Labels: feature ✨

#21 feat: 소셜 로그인 API
  .gitignore
  build.gradle
  src/main/java/com/flow/oauth/config/SecurityConfig.java
  src/main/java/com/flow/oauth/controller/OAuthController.java
  src/main/java/com/flow/oauth/domain/OAuthAttributes.java
  src/main/java/com/flow/oauth/domain/UserProfile.java
  src/main/java/com/flow/oauth/service/OAuthService.java
  src/main/java/com/flow/user/domain/SocialType.java
  src/main/java/com/flow/user/domain/User.java
  src/main/java/com/flow/user/repository/UserRepository.java
  src/main/java/com/flow/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature ✨
