Repository Flow-UMC/Flow-Server, pull requests merged in 2023-02, with the labels that each got.

#28 chore: 상세 내역 api 수정
  src/main/java/com/flow/detail/DetailDao.java
  src/main/java/com/flow/model/GetDetailRes.java
Labels: fix 🛠

#29 fix: 소셜 로그인 에러 수정
  .gitignore
  build.gradle
  src/main/java/com/flow/oauth/config/SecurityConfig.java
  src/main/java/com/flow/oauth/controller/OAuthController.java
  src/main/java/com/flow/oauth/domain/OAuthAttributes.java
  src/main/java/com/flow/oauth/domain/UserProfile.java
  src/main/java/com/flow/oauth/dto/OAuthAttributes.java
  src/main/java/com/flow/oauth/dto/SessionUser.java
  src/main/java/com/flow/oauth/service/OAuthService.java
  src/main/java/com/flow/user/domain/User.java
  src/main/java/com/flow/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: fix 🛠

#31 test: 소셜 로그인 DB 테스트
  src/main/java/com/flow/oauth/controller/OAuthController.java
  src/main/java/com/flow/user/domain/Budget.java
  src/main/java/com/flow/user/domain/User.java
Labels: test 🧪

#33 fix: Security 설정 변경
  src/main/java/com/flow/form/controller/FormController.java
  src/main/java/com/flow/form/domain/Form.java
  src/main/java/com/flow/form/dto/FormDto.java
  src/main/java/com/flow/form/repository/FormRepository.java
  src/main/java/com/flow/form/service/FormService.java
  src/main/java/com/flow/oauth/config/SecurityConfig.java
Labels: bug ⚠, fix 🛠

#36 Chore: 내역 상세, 카테고리 수정
  src/main/java/com/flow/category/CategoryDao.java
  src/main/java/com/flow/category/CategoryProvider.java
  src/main/java/com/flow/category/CategoryService.java
  src/main/java/com/flow/detail/DetailController.java
  src/main/java/com/flow/detail/DetailDao.java
  src/main/java/com/flow/detail/DetailProvider.java
  src/main/java/com/flow/detail/DetailService.java
  src/main/java/com/flow/model/GetCategoryRes.java
  src/main/java/com/flow/model/PatchDetailReq.java
Labels: fix 🛠

#37 feat: User 조회 API 추가
  src/main/java/com/flow/config/BaseResponseStatus.java
  src/main/java/com/flow/user/controller/UserController.java
  src/main/java/com/flow/user/domain/Budget.java
  src/main/java/com/flow/user/domain/User.java
  src/main/java/com/flow/user/dto/UserDto.java
  src/main/java/com/flow/user/dto/UserResponseDto.java
  src/main/java/com/flow/user/repository/UserRepository.java
  src/main/java/com/flow/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature ✨, fix 🛠

#39 fix: User, Budget 테이블명 수정
  src/main/java/com/flow/user/domain/Budget.java
  src/main/java/com/flow/user/domain/User.java
Labels: fix 🛠

#50 Chore: 홈, 카테고리 api 로직 변경
  src/main/java/com/flow/category/CategoryDao.java
  src/main/java/com/flow/home/HomeDao.java
  src/main/java/com/flow/home/HomeProvider.java
Labels: fix 🛠

#53 chore: 홈 월별 지출 금액 logic 수정
  src/main/java/com/flow/home/HomeDao.java
Labels: fix 🛠

#58 Chore: 홈, 카테고리 상세내역 api 예산 시작일 반영
  src/main/java/com/flow/home/HomeDao.java
  src/main/java/com/flow/home/HomeProvider.java
Labels: feature ✨, fix 🛠
